compras/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include(('home.urls','home'),namespace='home')),
    path('inv/',include(('inv.urls','inv'),namespace='inv')),
    path('admin/', admin.site.urls),
    path('coms/',include(('coms.urls','coms'),namespace='coms')),
    path('fac/',include(('fac.urls','coms'),namespace='fac')),
    path('estudiantes/',include(('estudiantes.urls','estudiantes'),namespace='estudiantes')),
]

estudiantes/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import ListarEstudiantes,NuevoEstudiante, ListarClubes, NuevoClub, consulta, EstudiantesList, EstudiantesList2

urlpatterns=[
    path('estudiantes/',ListarEstudiantes.as_view(),name='listarestudiantes'),
    path('estudiantes/prueba',consulta,name='consultajoin'),
    path('estudiantes/new',NuevoEstudiante.as_view(),name='insertarEstudiante'),
    path('clubes/',ListarClubes.as_view(),name='listarclubes'),
    path('clubes/new',NuevoClub.as_view(),name='insertarClub'),
    path('estudiantesjson/', EstudiantesList,name='listarestudiantes2'),
    path('estudiantesjson1/', EstudiantesList2.as_view(),name='listarestudiantes3'),
]

fac/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import ListarClientes
urlpatterns=[
    path('clientes/',ListarClientes.as_view(),name='listarclientes'),
]

estudiantes/models.py
from django.db import models

# Create your models here.
class Estudiante(models.Model):
    nombres=models.CharField(max_length=100)
    apellidos=models.CharField(max_length=100)
    fecha_nacimiento=models.DateField(null=True,
    blank=True
    )
    direccion=models.CharField(max_length=50)
    def __str__(self):
        return '{} {}'.format(self.nombres,self.apellidos)
    class Meta:
        verbose_name_plural="Estudiantes"

class ClubDeportivo(models.Model):
    nombre=models.CharField(max_length=50)
    estudiante=models.ForeignKey(Estudiante, on_delete=models.CASCADE)
    def __str__(self):
        return '{}'.format(self.nombre)
    class Meta:
        verbose_name_plural="Clubes"

estudiantes/forms.py
from django import forms
from estudiantes.models import Estudiante, ClubDeportivo
class EstudianteForm(forms.ModelForm):
    class Meta:
        model=Estudiante
        fields=['nombres', 'apellidos','fecha_nacimiento',
            'direccion'
        ]
        widget={'nombres':forms.TextInput(),'apellidos':forms.TextInput(),
        'fecha_nacimiento':forms.DateField(),'direccion':forms.TextInput()
        }
        def __init__(self,*args,**kwargs):
            super().__init__(*args,**kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class':'form-control'
                })
class ClubForm(forms.ModelForm):
    estudiante = forms.ModelChoiceField(
        queryset=Estudiante.objects.order_by('apellidos')
    )
    class Meta:
        model=ClubDeportivo
        fields=['nombre', 'estudiante'
        ]
        widget={'nombres':forms.TextInput()
        }
        def __init__(self,*args,**kwargs):
            super().__init__(*args,**kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class':'form-control'
                })

estudiantes/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from .models import Estudiante, ClubDeportivo
from django.urls import reverse_lazy
from estudiantes.forms import EstudianteForm, ClubForm
from django.contrib.auth.mixins import LoginRequiredMixin

from django.http import JsonResponse
from rest_framework.views import APIView
from rest_framework.response import Response
from .serializers import EsutianteSerializado
# Create your views here.
class ListarEstudiantes(LoginRequiredMixin,generic.ListView):
    model=Estudiante
    template_name="estudiantes/estudiantes_list.html"
    context_object_name="obj"
    login_url="home:login"
class NuevoEstudiante(LoginRequiredMixin,generic.CreateView):
    model=Estudiante
    template_name="estudiantes/estudiante_form.html"
    context_object_name="obj"
    form_class=EstudianteForm
    success_url=reverse_lazy("estudiantes:listarestudiantes")
    login_url="home:login"
class ListarClubes(LoginRequiredMixin,generic.ListView):
    model=ClubDeportivo
    template_name="estudiantes/clubes_list.html"
    context_object_name="obj"
    login_url="home:login"
class NuevoClub(LoginRequiredMixin,generic.CreateView):
    model=ClubDeportivo
    template_name="estudiantes/club_form.html"
    context_object_name="obj"
    form_class=ClubForm
    success_url=reverse_lazy("estudiantes:listarclubes")
    login_url="home:login"
def consulta(request):
    from django.db import connection
    with connection.cursor as cursor:
        cursor.execute("select * from estudiantes_estudiante as e join estudiantes_clubdeportivo as c on e.id=c.estudiante_id")
        rawData=cursor.fetchall()
        result=[]
        for r in rawData:
            result.append(list(r))
        contexto={"obj",result}
    return render(request,'estudiantes/consulta.html',contexto)
def EstudiantesList(request):
    MAX_OBJECTS = 200
    est = Estudiante.objects.all()[:MAX_OBJECTS]
    data = {"results": list(est.values("nombres","apellidos"))}
    return JsonResponse(data)
def Estudiante_detalle(request,pk):
    est = get_object_or_404(Estudiante, pk=pk)
    data = {"results": {
        "nombres": est.nombres,
        "apellidos": est.apellidos
        }}
    return JsonResponse(data)
class EstudiantesList2(APIView):
    def get(self,request):
        estuidantes= Estudiante.objects.all()
        data=EsutianteSerializado(estuidantes, many=True).data
        return Response(data)

estudiantes/templates/estudiantes/club_form.html
{% extends 'base/base.html' %}
{% block page_conent %}
<form method="post">
    {{form.as_p}}
    {%  csrf_token %}
    <button type="submit" class="btn btn-primary">Agregar</button>
    <a href="{% url 'estudiantes:listarclubes' %}" class="btn btn-success"><span class="fa fa-undo"></span>Regresar</a>
</form>
{% endblock %}
{% block js_page %}{% endblock %}

estudiantes/templates/estudiantes/clubes_list.html
{% extends 'base/base.html' %}
{% block page_conent %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Acciones</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item"  href="{% url 'estudiantes:insertarClub'%}">Nueva</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </div>
    </div>
    
    <div class="card-body">
        {% if not obj %}
        Sin Estudiantes
        {% endif %}
        <table class="table table-striped table-hover" id="table">
            <thead>
                <th>Id</th>
                <th>Nombre</th>
                <th>Estudiante</th>
                <th>Acciones</th>
                
            </thead>
            <tbody>
                
                {% for item in obj %}
                    <tr>
                        <td>{{item.id}}</td>
                        <td>{{item.nombre}}</td>
                        <td>{{item.estudiante}}</td>
                        

                        <td><a href ="#" class="btn btn-warning btn-circle" role="button" onclick="return abrir_modal('{#  url 'inv:EditarProducto' item.id //#endregion}')"><span class="fab fa-adn"></span></a>
                            <a href="{# url 'inv:Productoinactivar' item.id #}" class="btn btn-danger btn-circle" role="button"><span class="fas fa-arrow-alt-circle-left"></span></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block js_page %}
<script>
    $(document).ready( function () {
    $('#table').DataTable();
} );
</script>
{% endblock %}

estudiantes/templates/estudiantes/consulta.html
{% extends 'base/base.html' %}
{% block page_conent %}
{% endblock %}

estudiantes/templates/estudiantes/estudiante_form.html
{% extends 'base/base.html' %}
{% block page_conent %}
<form method="post">
    {{form.as_p}}
    {%  csrf_token %}
    <button type="submit" class="btn btn-primary">Agregar</button>
    <a href="{% url 'estudiantes:listarestudiantes' %}" class="btn btn-success"><span class="fa fa-undo"></span>Regresar</a>
</form>
{% endblock %}
{% block js_page %}{% endblock %}

estudiantes/templates/estudiantes/estudiante_list.html
{% extends 'base/base.html' %}
{% block page_conent %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Acciones</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item"  href="{% url 'estudiantes:insertarEstudiante'%}">Nueva</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </div>
    </div>
    
    <div class="card-body">
        {% if not obj %}
        Sin Estudiantes
        {% endif %}
        <table class="table table-striped table-hover" id="table">
            <thead>
                <th>Id</th>
                <th>Nombres</th>
                <th>Apellidos</th>
                <th>Fecha de nacimiento</th>
                <th>Direción</th>
                <th>Acciones</th>
                
            </thead>
            <tbody>
                
                {% for item in obj %}
                    <tr>
                        <td>{{item.id}}</td>
                        <td>{{item.nombres}}</td>
                        <td>{{item.apellidos}}</td>
                        <td>{{item.fecha_nacimiento |date:"d/m/Y "}}</td>
                        <td>{{item.direccion}}</td>

                        <td><a href ="#" class="btn btn-warning btn-circle" role="button" onclick="return abrir_modal('{#  url 'inv:EditarProducto' item.id //#endregion}')"><span class="fab fa-adn"></span></a>
                            <a href="{# url 'inv:Productoinactivar' item.id #}" class="btn btn-danger btn-circle" role="button"><span class="fas fa-arrow-alt-circle-left"></span></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block js_page %}
<script>
    $(document).ready( function () {
    $('#table').DataTable();
} );
</script>
{% endblock %}