compras/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include(('home.urls','home'),namespace='home')),
    path('inv/',include(('inv.urls','inv'),namespace='inv')),
    path('admin/', admin.site.urls),
    path('coms/',include(('coms.urls','coms'),namespace='coms')),
    path('fac/',include(('fac.urls','coms'),namespace='fac')),
    path('estudiantes/',include(('estudiantes.urls','estudiantes'),namespace='estudiantes')),
]

fac/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import ListarClientes
urlpatterns=[
    path('clientes/',ListarClientes.as_view(),name='listarclientes'),
]

inv/urls.py
from django.contrib import admin
from django.urls import include, path
from inv.views import ListarCategorias, InsertarCategoria,EditarCategoria, BorrarCategoria, ListarSubCategorias, \
    InsertarSubCategoria, EditarSubCategoria, BorrarSubCategoria, ListarMarcas, InsertarMarca, EditarMarca, marca_incativar, \
        ListarUM, InsertarUM, EditarUM, UM_incativar, ListarProductos, Producto_incativar, InsertarProducto, EditarProducto

urlpatterns=[
    path('categorias/',ListarCategorias.as_view(),name='listarcategorias'),
    path('categorias/new',InsertarCategoria.as_view(),name='nuevacategoria'),
    path('categorias/edit/<int:pk>',EditarCategoria.as_view(),name='editarcategoria'),
    path('categorias/delete/<int:pk>',BorrarCategoria.as_view(),name='BorrarCategoria'),


    path('subcategorias/',ListarSubCategorias.as_view(),name='listarsubcategorias'),
    path('subcategorias/new',InsertarSubCategoria.as_view(),name='nuevasubcategoria'),
    path('subcategorias/edit/<int:pk>',EditarSubCategoria.as_view(),name='editarsubcategoria'),
    path('subcategorias/delete/<int:pk>',BorrarSubCategoria.as_view(),name='BorrarSubCategoria'),

    path('marcas/',ListarMarcas.as_view(),name='listarmarcas'),
    path('marcas/new',InsertarMarca.as_view(),name='nuevamarca'),
    path('marcas/edit/<int:pk>',EditarMarca.as_view(),name='editarmarca'),
    path('marca/inactivar/<int:id>',marca_incativar,name='marcainactivar'),

    path('UM/',ListarUM.as_view(),name='listarUM'),
    path('UM/new',InsertarUM.as_view(),name='NuevoUM'),
    path('UM/edit/<int:pk>',EditarUM.as_view(),name='EditarUM'),
    path('UM/inactivar/<int:id>', UM_incativar,name="UMinactivar"),


    path('productos/',ListarProductos.as_view(),name='listarproductos'),
    path('productos/inactivar/<int:id>', Producto_incativar,name="Productoinactivar"),
    path('producto/new',InsertarProducto.as_view(),name='NuevoProducto'),
    path('producto/edit/<int:pk>',EditarProducto.as_view(),name='EditarProducto'),
]

inv/models.py
from django.db import models
from home.models import clasemodelo
# Create your models here.
class Categoria(clasemodelo):
    descripcion=models.CharField(
        max_length=100,
        help_text='Descripción del producto' #cuando creo el formulario en django hay un cambio
    )
    def __str__(self): #Para mostar cuando se llama y que aparezca la descripción no el valor hexadecimal
        return '{}'.format(self.descripcion)
    class Meta:
        verbose_name_plural="Categorias"
class SubCategoria(clasemodelo):
    categoria=models.ForeignKey(Categoria, on_delete=models.CASCADE)
    descripcion=models.CharField(
        max_length=100,
        help_text='Descripción del producto' #cuando creo el formulario en django hay un cambio
    )
    def __str__(self): #Para mostar cuando se llama y que aparezca la descripción no el valor hexadecimal
        return '{}:{}'.format(self.descripcion,self.categoria.descripcion)
    class Meta:
        verbose_name_plural="SubCategorias"
        unique_together =('categoria', 'descripcion')
class Marca(clasemodelo):
    descripcion=models.CharField(
        max_length=100,
        help_text='Nombre de la Marca' #cuando creo el formulario en django hay un cambio
    )
    def __str__(self): #Para mostar cuando se llama y que aparezca la descripción no el valor hexadecimal
        return '{}'.format(self.descripcion)
    class Meta:
        verbose_name_plural="Marcas"
class UM(clasemodelo):
    descripcion=models.CharField(
        max_length=100,
        help_text='Descripción de la Unidad de Medidad' #cuando creo el formulario en django hay un cambio
    )
    def __str__(self): #Para mostar cuando se llama y que aparezca la descripción no el valor hexadecimal
        return '{}'.format(self.descripcion)
    class Meta:
        verbose_name_plural="Unidades de Medida"
class Producto(clasemodelo):
    codigo=models.CharField(
        max_length=20,
        unique=True
    )
    codigo_barra=models.CharField(max_length=50)
    descripcion=models.CharField(max_length=100)
    existencia=models.IntegerField(default=0)
    ultima_compra=models.DateField(null=True, blank=True)
    precio=models.FloatField(default=0)

    marca=models.ForeignKey(Marca, on_delete=models.CASCADE)
    unidad_medida=models.ForeignKey(UM, on_delete=models.CASCADE)
    subcategoria=models.ForeignKey(SubCategoria, on_delete=models.CASCADE)
    
    def __str__(self):
        return '{}'.format(self.descripcion)
    class Meta:
        verbose_name_plural="productos"
        unique_together =('codigo', 'codigo_barra')

inv/forms.py
from django import forms
from inv.models import Categoria, SubCategoria, Marca, UM, Producto
class CategoriaForm(forms.ModelForm):
    class Meta:
        model=Categoria
        fields = ['descripcion','estado']
        labels = {'descripcion':'Comentarios de la categoria',"estado":"Estado de la categora"}
        widget={'descripcion':forms.TextInput}

        def __init__(self,*args,**kwargs):
            super().__init__(*args,**kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class':'form-control'
                })
class SubCategoriaForm(forms.ModelForm):
    categoria = forms.ModelChoiceField(
        queryset=Categoria.objects.filter(estado=True).order_by('descripcion') #Hacer un filtro y ordenar por un elemento utilizando ORM django
    )
    class Meta:
        model=SubCategoria
        fields = ['categoria','descripcion','estado']
        labels = {'descripcion':'Comentarios de la Subcategoria',"estado":"Estado de la categora"}
        widget={'descripcion':forms.TextInput}

        def __init__(self,*args,**kwargs):
            super().__init__(*args,**kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class':'form-control'
                })
            self.fields['categoria'].empty_label= "Seleccione Categoria"
class MarcaForm(forms.ModelForm):
    class Meta:
        model=Marca
        fields = ['descripcion','estado']
        labels = {'descripcion':'Nombre de la marca',"estado":"Estado de la categora"}
        widget={'descripcion':forms.TextInput}

        def __init__(self,*args,**kwargs):
            super().__init__(*args,**kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class':'form-control'
                })
class UMForm(forms.ModelForm):
    class Meta:
        model=UM
        fields = ['descripcion','estado']
        labels = {'descripcion':'Tipo de medida',"estado":"Estado de la categora"}
        widget={'descripcion':forms.TextInput}

        def __init__(self,*args,**kwargs):
            super().__init__(*args,**kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class':'form-control'
                })
class ProductoForm(forms.ModelForm):
    class Meta:
        model = Producto
        fields=['codigo','codigo_barra','descripcion','estado',
            'precio','existencia','ultima_compra','marca',
            'subcategoria','unidad_medida']
        exclude=['um','fm','uc','fc']
        widget={'descripcion':forms.TextInput()}
        def __init__(self,*args,**kwargs):
            super.__init__(*args,**kwargs)
            for field in iter(self.fields):
                self.fields[field].widget.attrs.update({
                    'class':'form-control'
                })
            self.fields['ultima_compra'].widget.attrs['readonly'] = True
            self.fields['existencia'].widget.attrs['readonly'] = True

inv/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from inv.models import Categoria, SubCategoria, Marca, UM, Producto
from inv.forms import CategoriaForm, SubCategoriaForm, MarcaForm, UMForm, ProductoForm
from django.urls import reverse_lazy
from home.views import Sinprivilegios
# Create your views here.
class ListarCategorias(LoginRequiredMixin,PermissionRequiredMixin,generic.ListView):
    model=Categoria
    permission_required="inv.view_categoria"
    template_name="inv/categoria_list.html"
    context_object_name="obj"
    login_url="home:login"
    
class InsertarCategoria(SuccessMessageMixin,PermissionRequiredMixin,LoginRequiredMixin, \
    generic.CreateView):
    model=Categoria
    template_name="inv/categoria_form.html"
    permission_required="inv.view_categoria"
    context_object_name="obj"
    form_class=CategoriaForm
    success_url=reverse_lazy("inv:listarcategorias")
    login_url="home:login"
    success_message="Categoria creada melo"
    def form_valid(self, form):
        form.instance.uc=self.request.user
        return super().form_valid(form)
class EditarCategoria(SuccessMessageMixin,LoginRequiredMixin, \
    generic.UpdateView):
    model=Categoria
    template_name="inv/categoria_form.html"
    permission_required="inv.view_categoria"
    context_object_name="obj"
    
    form_class=CategoriaForm
    success_url=reverse_lazy("inv:listarcategorias")
    login_url="home:login"
    success_message="Categoria editada melo"
    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)
class BorrarCategoria(LoginRequiredMixin, generic.DeleteView):
    model=Categoria
    template_name="inv/catalogos_delete.html"
    context_object_name="obj"
    form_class=CategoriaForm
    success_url=reverse_lazy("inv:listarcategorias")
    login_url="home:login"
class ListarSubCategorias(LoginRequiredMixin, Sinprivilegios ,generic.ListView):
    model=SubCategoria
    template_name="inv/Subcategoria_list.html"
    permission_required="inv.view_subcategoria"
    context_object_name="obj"
    login_url="home:login"
class InsertarSubCategoria(LoginRequiredMixin, generic.CreateView):
    model=SubCategoria
    template_name="inv/Subcategoria_form.html"
    context_object_name="obj"
    form_class=SubCategoriaForm
    success_url=reverse_lazy("inv:listarsubcategorias")
    login_url="home:login"
    def form_valid(self, form):
        form.instance.uc=self.request.user
        return super().form_valid(form)
class EditarSubCategoria(LoginRequiredMixin, generic.UpdateView):
    model=SubCategoria
    template_name="inv/Subcategoria_form.html"
    context_object_name="obj"
    form_class=SubCategoriaForm
    success_url=reverse_lazy("inv:listarsubcategorias")
    login_url="home:login"
    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)
class BorrarSubCategoria(LoginRequiredMixin, generic.DeleteView):
    model=SubCategoria
    template_name="inv/catalogos_delete.html"
    context_object_name="obj"
    form_class=SubCategoriaForm
    success_url=reverse_lazy("inv:listarsubcategorias")
    login_url="home:login"

class ListarMarcas(LoginRequiredMixin,Sinprivilegios,generic.ListView):
    model=Marca
    template_name="inv/marca_list.html"
    permission_required="inv.view_marca"
    context_object_name="obj"
    login_url="home:login"
class InsertarMarca(LoginRequiredMixin, generic.CreateView):
    model=Marca
    template_name="inv/marca_form.html"
    context_object_name="obj"
    form_class=MarcaForm
    success_url=reverse_lazy("inv:listarmarcas")
    login_url="home:login"
    def form_valid(self, form):
        form.instance.uc=self.request.user
        return super().form_valid(form)
class EditarMarca(LoginRequiredMixin, generic.UpdateView):
    model=Marca
    template_name="inv/marca_form.html"
    context_object_name="obj"
    form_class=MarcaForm
    success_url=reverse_lazy("inv:listarmarcas")
    login_url="home:login"
    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)
def marca_incativar(request, id):
    marca = Marca.objects.filter(pk=id).first()
    contexto={}
    template_name="inv/catalogos_delete.html"
    if not marca:
        return redirect("inv:listarmarcas")
    if request.method=='GET':
        contexto={'obj':marca}
    if request.method=='POST': #Para actualizar datos desde una vista
        marca.estado=False
        marca.save()
        return redirect("inv:listarmarcas")
    return render(request, template_name, contexto)
class ListarUM(LoginRequiredMixin,generic.ListView):
    model=UM
    template_name="inv/UM_list.html"
    context_object_name="obj"
    login_url="home:login"
class InsertarUM(LoginRequiredMixin, generic.CreateView):
    model=UM
    template_name="inv/UM_form.html"
    context_object_name="obj"
    form_class=UMForm
    success_url=reverse_lazy("inv:listarUM")
    login_url="home:login"
    def form_valid(self, form):
        form.instance.uc=self.request.user
        return super().form_valid(form)
class EditarUM(LoginRequiredMixin, generic.UpdateView):
    model=UM
    template_name="inv/UM_form.html"
    context_object_name="obj"
    form_class=UMForm
    success_url=reverse_lazy("inv:listarUM")
    login_url="home:login"
    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)
def UM_incativar(request, id):
    um = UM.objects.filter(pk=id).first()
    contexto={}
    template_name="inv/catalogos_delete.html"
    if not um:
        return redirect("inv:listarUM")
    if request.method=='GET':
        contexto={'obj':um}
    if request.method=='POST': #Para actualizar datos desde una vista
        um.estado=False
        um.save()
        return redirect("inv:listarUM")
    return render(request, template_name, contexto)
class ListarProductos(LoginRequiredMixin,generic.ListView):
    model=Producto
    template_name="inv/producto_list.html"
    context_object_name="obj"
    login_url="home:login"
    def form_valid(self, form):
        form.instance.uc=self.request.user
        return super().form_valid(form)
def Producto_incativar(request, id):
    producto = Producto.objects.filter(pk=id).first()
    contexto={}
    template_name="inv/catalogos_delete.html"
    if not Producto:
        return redirect("inv:listarproductos")
    if request.method=='GET':
        contexto={'obj':producto}
    if request.method=='POST': #Para actualizar datos desde una vista
        producto.estado=False
        producto.save()
        return redirect("inv:listarproductos")
    return render(request, template_name, contexto)
class InsertarProducto(LoginRequiredMixin, generic.CreateView):
    model=Producto
    template_name="inv/producto_form.html"
    context_object_name="obj"
    form_class=ProductoForm
    success_url=reverse_lazy("inv:listarproductos")
    login_url="home:login"
    def form_valid(self, form):
        form.instance.uc=self.request.user
        return super().form_valid(form)
class EditarProducto(LoginRequiredMixin, generic.UpdateView):
    model=Producto
    template_name="inv/producto_form.html"
    context_object_name="obj"
    form_class=ProductoForm
    success_url=reverse_lazy("inv:listarproductos")
    login_url="home:login"
    def form_valid(self, form):
        form.instance.um = self.request.user.id
        return super().form_valid(form)

inv/templates/inv/UM_list.html
{% extends 'base/base.html' %}
{% block page_conent %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Acciones</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" href="{% url 'inv:NuevoUM' %}">Nueva</a>
                
            </div>
        </div>
    </div>
    
    <div class="card-body">
        {% if not obj %}
        No hay Marcas registradas
        {% endif %}
        <table class="table table-striped table-hover" id="table">
            <thead>
                <th>Id</th>
                <th>Descripción</th>
                <th>Estado</th>
                <th>Fecha creado</th>
                <th>Fecha modificado</th>
                <th class="all">Acción</th>
            </thead>
            <tbody>
                
                {% for item in obj %}
                    <tr>
                        <td>{{item.id}}</td>
                        <td>{{item.descripcion}}</td>
                        <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
                        <td>{{item.fc|date:"d/m/Y H:i:s"}}</td>
                        <td>{{item.fm|date:"d/m/Y H:i:s"}}</td>
                        <td><a href ="{% url 'inv:EditarUM' item.id %}" class="btn btn-warning btn-circle" role="button">Editar</a>
                            <a href="{% url 'inv:UMinactivar' item.id %}" class="btn btn-danger btn-circle" role="button">Borrar</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block js_page %}
<script>
    $(document).ready( function () {
    $('#table').DataTable();
} );
</script>

{% endblock %}

inv/templates/inv/categoria_list.html
{% extends 'base/base.html' %}
{% block page_conent %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Acciones</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" href="{% url 'inv:nuevacategoria' %}">Nueva</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </div>
    </div>
    
    <div class="card-body">
        {% if not obj %}
        No hay categoria
        {% endif %}
        <table class="table table-striped table-hover" id="table">
            <thead>
                <th>Id</th>
                <th>Descripción</th>
                <th>Estado</th>
                <th>Fecha creado</th>
                <th>Fecha modificado</th>
                <th class="all">Acción</th>
            </thead>
            <tbody>
                
                {% for item in obj %}
                    <tr>
                        <td>{{item.id}}</td>
                        <td>{{item.descripcion}}</td>
                        <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
                        <td>{{item.fc|date:"d/m/Y H:i:s"}}</td>
                        <td>{{item.fm|date:"d/m/Y H:i:s"}}</td> 
                        <td><a href ="{% url 'inv:editarcategoria' item.id %}" class="btn btn-warning btn-circle" role="button"><span class="fab fa-adn"></span></a>
                            <a href="{% url 'inv:BorrarCategoria' item.id %}" class="btn btn-danger btn-circle" role="button"><span class="fas fa-arrow-alt-circle-left"></span></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block js_page %}
<script>
    $(document).ready( function () {
    $('#table').DataTable();
} );
</script>

{% endblock %}

inv/templates/inv/marca_list.html
{% extends 'base/base.html' %}
{% block page_conent %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Acciones</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" href="{% url 'inv:nuevamarca' %}">Nueva</a>
                
            </div>
        </div>
    </div>
    
    <div class="card-body">
        {% if not obj %}
        No hay Marcas registradas
        {% endif %}
        <table class="table table-striped table-hover" id="table">
            <thead>
                <th>Id</th>
                <th>Descripción</th>
                <th>Estado</th>
                <th>Fecha creado</th>
                <th>Fecha modificado</th>
                <th class="all">Acción</th>
            </thead>
            <tbody>
                
                {% for item in obj %}
                    <tr>
                        <td>{{item.id}}</td>
                        <td>{{item.descripcion}}</td>
                        <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
                        <td>{{item.fc|date:"d/m/Y H:i:s"}}</td>
                        <td>{{item.fm|date:"d/m/Y H:i:s"}}</td>
                        <td><a href ="{% url 'inv:editarmarca' item.id %}" class="btn btn-warning btn-circle" role="button">Editar</a>
                            <a href="{% url 'inv:marcainactivar' item.id %}" class="btn btn-danger btn-circle" role="button">Borrar</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block js_page %}
<script>
    $(document).ready( function () {
    $('#table').DataTable();
} );
</script>

{% endblock %}

inv/templates/inv/producto_list.html
{% extends 'base/base.html' %}
{% block page_conent %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Acciones</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" onclick="return abrir_modal('{%  url 'inv:NuevoProducto'%}')" href="#">Nueva</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </div>
    </div>
    
    <div class="card-body">
        {% if not obj %}
        Sin productos disponibles
        {% endif %}
        <table class="table table-striped table-hover" id="table">
            <thead>
                <th>Id</th>
                <th>Descripción</th>
                <th>Código</th>
                <th>Código Barra</th>
                <th>Existencias</th>
                <th>Precio</th>
                <th>Estado</th>
                <th>Fecha creado</th>
                <th>Fecha modificado</th>
                <th class="all">Acción</th>
            </thead>
            <tbody>
                
                {% for item in obj %}
                    <tr>
                        <td>{{item.id}}</td>
                        <td>{{item.codigo}}</td>
                        <td>{{item.codigo_barra}}</td>
                        <td>{{item.descripcion}}</td>
                        <td>{{item.existencia}}</td>
                        <td>{{item.precio}}</td>
                        <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
                        <td>{{item.fc|date:"d/m/Y H:i:s"}}</td>
                        <td>{{item.fm|date:"d/m/Y H:i:s"}}</td>
                        <td><a href ="#" class="btn btn-warning btn-circle" role="button" onclick="return abrir_modal('{%  url 'inv:EditarProducto' item.id %}')"><span class="fab fa-adn"></span></a>
                            <a href="{% url 'inv:Productoinactivar' item.id %}" class="btn btn-danger btn-circle" role="button"><span class="fas fa-arrow-alt-circle-left"></span></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block js_page %}
<script>
    $(document).ready( function () {
    $('#table').DataTable();
} );
</script>

{% endblock %}

inv/templates/inv/subcategoria_list.html
{% extends 'base/base.html' %}
{% block page_conent %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Acciones</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" href="{% url 'inv:nuevasubcategoria' %}">Nueva</a>
               
            </div>
        </div>
    </div>
    
    <div class="card-body">
        {% if not obj %}
        No hay Sub categoría
        {% endif %}
        <table class="table table-striped table-hover" id="table">
            <thead>
                <th>Categoria</th>
                <th>Id</th>
                <th>Descripción</th>
                <th>Estado</th>
                <th>Fecha creado</th>
                <th>Fecha modificado</th>
                <th class="all">Acción</th>
            </thead>
            <tbody>
                
                {% for item in obj %}
                    <tr>
                        <td>{{item.categoria}}</td>
                        <td>{{item.id}}</td>
                        <td>{{item.descripcion}}</td>
                        <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
                        <td>{{item.fc|date:"d/m/Y H:i:s"}}</td>
                        <td>{{item.fm|date:"d/m/Y H:i:s"}}</td>
                        <td><a href ="{% url 'inv:editarsubcategoria' item.id %}" class="btn btn-warning btn-circle" role="button"></a>
                            <a href="{% url 'inv:BorrarSubCategoria' item.id %}" class="btn btn-danger btn-circle" role="button"></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block js_page %}
<script>
    $(document).ready( function () {
    $('#table').DataTable();
} );
</script>

{% endblock %}