compras/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('',include(('home.urls','home'),namespace='home')),
    path('inv/',include(('inv.urls','inv'),namespace='inv')),
    path('admin/', admin.site.urls),
    path('coms/',include(('coms.urls','coms'),namespace='coms')),
    path('fac/',include(('fac.urls','coms'),namespace='fac')),
    path('estudiantes/',include(('estudiantes.urls','estudiantes'),namespace='estudiantes')),
]

coms/urls.py
from django.contrib import admin
from django.urls import include, path
from coms.views import ComprasView
from coms.report import reporte
urlpatterns=[
    path('coms/',ComprasView.as_view(),name='listarcompras'),
    path('coms/imprimir',reporte,name='imprimirproductos'),
]

fac/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import ListarClientes
urlpatterns=[
    path('clientes/',ListarClientes.as_view(),name='listarclientes'),
]

inv/urls.py
from django.contrib import admin
from django.urls import include, path
from inv.views import ListarCategorias, InsertarCategoria,EditarCategoria, BorrarCategoria, ListarSubCategorias, \
    InsertarSubCategoria, EditarSubCategoria, BorrarSubCategoria, ListarMarcas, InsertarMarca, EditarMarca, marca_incativar, \
        ListarUM, InsertarUM, EditarUM, UM_incativar, ListarProductos, Producto_incativar, InsertarProducto, EditarProducto

urlpatterns=[
    path('categorias/',ListarCategorias.as_view(),name='listarcategorias'),
    path('categorias/new',InsertarCategoria.as_view(),name='nuevacategoria'),
    path('categorias/edit/<int:pk>',EditarCategoria.as_view(),name='editarcategoria'),
    path('categorias/delete/<int:pk>',BorrarCategoria.as_view(),name='BorrarCategoria'),


    path('subcategorias/',ListarSubCategorias.as_view(),name='listarsubcategorias'),
    path('subcategorias/new',InsertarSubCategoria.as_view(),name='nuevasubcategoria'),
    path('subcategorias/edit/<int:pk>',EditarSubCategoria.as_view(),name='editarsubcategoria'),
    path('subcategorias/delete/<int:pk>',BorrarSubCategoria.as_view(),name='BorrarSubCategoria'),

    path('marcas/',ListarMarcas.as_view(),name='listarmarcas'),
    path('marcas/new',InsertarMarca.as_view(),name='nuevamarca'),
    path('marcas/edit/<int:pk>',EditarMarca.as_view(),name='editarmarca'),
    path('marca/inactivar/<int:id>',marca_incativar,name='marcainactivar'),

    path('UM/',ListarUM.as_view(),name='listarUM'),
    path('UM/new',InsertarUM.as_view(),name='NuevoUM'),
    path('UM/edit/<int:pk>',EditarUM.as_view(),name='EditarUM'),
    path('UM/inactivar/<int:id>', UM_incativar,name="UMinactivar"),


    path('productos/',ListarProductos.as_view(),name='listarproductos'),
    path('productos/inactivar/<int:id>', Producto_incativar,name="Productoinactivar"),
    path('producto/new',InsertarProducto.as_view(),name='NuevoProducto'),
    path('producto/edit/<int:pk>',EditarProducto.as_view(),name='EditarProducto'),
]

coms/models.py
from django.db import models
from home.models import clasemodelo
from inv.models import Producto
# Create your models here.
class ComprasEnc(clasemodelo):
    fecha_compra=models.DateField(null=True, blank=True)
    observacion=models.TextField(blank=True,null=True)
    no_factura=models.CharField(max_length=100)
    fecha_factura=models.DateField()
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)

    def __str__(self):
        return '{}'.format(self.observacion)
    def save(self):
        self.total=self.sub_total-self.descuento
        super(ComprasEnc,self).save()
    class Meta:
        verbose_name_plural="Encabezado compras"
        verbose_name="encabezado compra"
class ComprasDet(clasemodelo):
    compra=models.ForeignKey(ComprasEnc,on_delete=models.CASCADE)
    producto=models.ForeignKey(Producto,on_delete=models.CASCADE)
    cantidad=models.BigIntegerField(default=0)
    precio_prv=models.FloatField(default=0)
    sub_total=models.FloatField(default=0)
    descuento=models.FloatField(default=0)
    total=models.FloatField(default=0)
    costo=models.FloatField(default=0)
    def __str__(self):
        return '{}'.format(self.producto)
    def save(self):
        self.sub_total=float(self.cantidad*self.precio_prv)
        self.total=self.sub_total-float(self.descuento)
        super(ComprasDet,self).save()
    class Meta:
        verbose_name_plural="detalles compras"
        verbose_name="detalle compra"

coms/forms.py
from django import forms
from .models import ComprasEnc

class ComprasEncForm(forms.ModelForm):
    fecha_compra=forms.DateInput()
    fecha_factura=forms.DateInput()

    class Meta:
        model=ComprasEnc
        fields=['fecha_compra','observacion','no_factura','fecha_factura',
        'sub_total','descuento','total']
    def __init(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class':'form-control'
            })
        self.fields['fecha_compra'].widget.attrs['readonly']=True
        self.fields['fecha_factura'].widget.attrs['readonly']=True
        self.fields['sub_total'].widget.attrs['readonly']=True
        self.fields['total'].widget.attrs['readonly']=True

coms/views.py
from django.shortcuts import render
from django.views import generic
from coms.models import ComprasEnc, ComprasDet
from inv.models import Producto
from home.views import Sinprivilegios
from coms.forms import ComprasEncForm
import datetime
from django.http import HttpResponse
# Create your views here.
class ComprasView( Sinprivilegios,generic.ListView):
    model=ComprasEnc
    template_name="coms/compras_list.html"
    permission_required="coms.view_comprasenc"
    context_object_name="obj"

def compras(request, compra_id=None):
    template_name="coms/compras.html"
    prod=Producto.objects.filter(estado=True)
    form_compras={}
    contexto={}

    if request.method=='GET':
        form_compras=ComprasEncForm()
        enc=ComprasEnc.objects.filter(pk=compra_id).first()
    
    if enc:
        det=ComprasEnc.object.filter(compras=enc)
        fecha_compra=datetime.date.isoformat(enc.fecha_compra)
        fecha_factura=datetime.date.isoformat(enc.fecha_factura)
        e:{
            'fecha_compra':fecha_compra,
            'fecha_factura':fecha_factura,
            'observacion':enc.observacion,
            'no_factura':enc.no_factura,
            'sub_total':enc.sub_total,
            'descuento':enc.descuento,
            'total':enc.total
        }
        form_compras=ComprasEncForm(e)
    else:
        det=None
    

    contexto={'productos':prod,'encabezado':enc,'detalle':det,'form_enc':form_compras}

    return render(request, template_name, contexto)

coms/templates/coms/compras.html
{% extends 'base/base.html' %}
{% block page_conent %}
<form method="post" id="fmcCompras">

    {%  csrf_token %}

    <div class="col-xl 12 col-md 12 mb 12">
        {% if encabezado %}
        <div class="card border-left-warning shadow h-100 py-2">
            {% else %}
            <div class="card border-left-success shadow h-100 py-2">
                {% endif %}
                <div class="card-body">
                    <div class="row no-gutters aling-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weigth-bold text-primary text-uppercase mb-1">
                                {% if encabezado %}Editar {% else %} Nueva {% endif %} Compra
                            </div>
                            <div class="row">
                                <div class="col-6"><label for="id_compra_fecha">Fecha Compra:</label></div>
                                <div class="col sm-10">
                                    {{form_enc.fecha_compra}}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-6"><label for="id_observacion">Descripción:</label></div>
                                <div class="col sm-10">
                                    {{form_enc.observacion}}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <button type="submit" class="btn btn-primary">Agregar</button>
            <a href="{% url 'inv:listarcategorias' %}" class="btn btn-success"><span
                    class="fa fa-undo"></span>Regresar</a>
</form>
{% endblock %}
{% block js_page %}{% endblock %}

coms/templates/coms/compras_list.html
{% extends 'base/base.html' %}
{% block page_conent %}
<!-- Dropdown Card Example -->
<div class="card shadow mb-4">
    <!-- Card Header - Dropdown -->
    <div class="card-header py-3 d-flex flex-row align-items-center justify-content-between">
        <h6 class="m-0 font-weight-bold text-primary">Acciones</h6>
        <div class="dropdown no-arrow">
            <a class="dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown"
                aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-ellipsis-v fa-sm fa-fw text-gray-400"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right shadow animated--fade-in" aria-labelledby="dropdownMenuLink">
                <div class="dropdown-header">Acciones:</div>
                <a class="dropdown-item" href="{% url 'inv:nuevacategoria' %}">Nueva</a>
                <a class="dropdown-item" href="#">Another action</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </div>
    </div>
    
    <div class="card-body">
        {% if not obj %}
        No hay Compras disponibles
        {% endif %}
        <table class="table table-striped table-hover" id="table">
            <thead>
                <th>Id</th>
                <th>Número de compra</th>
                <th>Observación</th>
                <th>Fecha de compra</th>
                <th>no_factura</th>
                <th>Fecha modificado</th>
                <th class="all">Acción</th>
            </thead>
            <tbody>
                
                {% for item in obj %}
                    <tr>
                        <td>{{item.id}}</td>
                        <td>{{item.no_factura}}</td>
                        <td>{{item.observacion}}</td>
                        <td>{{item.estado|yesno:"Activo,Inactivo"}}</td>
                        <td>{{item.fecha_compra|date:"d/m/Y H:i:s"}}</td>
                        <td>{{item.fecha_factura|date:"d/m/Y H:i:s"}}</td>
                        <td><a href ="{% url 'inv:editarcategoria' item.id %}" class="btn btn-warning btn-circle" role="button"><span class="fab fa-adn"></span></a>
                            <a href="{% url 'inv:BorrarCategoria' item.id %}" class="btn btn-danger btn-circle" role="button"><span class="fas fa-arrow-alt-circle-left"></span></a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

{% block js_page %}
<script>
    $(document).ready( function () {
    $('#table').DataTable();
} );
</script>

{% endblock %}